### ISSUE TITLE
Create CSS Classes for primary and secondary button

### ISSUE THREAD

**Issue by wisammechano** [Iraq-RBC-Capstones-2021/capstone-react-flashcards#5]
Using the @apply utility you can define classes for the primary and secondary buttons of the app to reduce incosistency. Below is an example:

```css
.btn-secondary {
  box-shadow: 2px 2px 0px theme('colors.black');
  @apply bg-white border-2 rounded-lg border-black py-1 px-2.5;
}
```

You should also add all the hover-related effects for this and the primary button. You can use the theme() [function](https://tailwindcss.com/docs/functions-and-directives#theme) to extract values from tailwind.

to experiment, you can checkout [tailwind playground ](https://play.tailwindcss.com/XEufqepwDA?file=css)
